// job('First-seed-project-Maven') {
//     description("First Maven seed job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
//     // logRotator(-1, 10)
//     // jdk('Java 8')
//     scm {
//         git('https://github.com/Balamurali81/java_project.git', 'simple')
//     }
//     triggers {
//         scm('* * * * *')
//     }
//     steps {
//         maven('clean build', 'java-tomcat-sample/pom.xml')
//     }
//     publishers {
//         archiveArtifacts '**/*.war'
//     }
// }