pipeline {
    agent any
    stages {
        stage ('Build Maven artifcat') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success{
                    archiveArtifacts artifacts: '**/*.war'
                }

            }
        }
        stage ('Create docker image for web appliation with Tomcat') {
            steps{
                sh "docker build -f java-tomcat-sample-docker/. -t tomcatsampeldockerwebapp:${env:BUILD_ID}"
            }
            
        }
    }
}