pipeline {
    agent any
    stages {
        stage ('Build Maven artifcat') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success{
                    archiveArtifacts artifacts: '**/*.war'
                }

            }
        }
        stage ('Copy artifcats to Staging') {
            steps {
                timeout(time: 5, unit: 'DAYS') { 
                input('Approve/Reject for stage deployment?')
                }
                build job: 'Code-Deploy-Staging'
            }
       }
        stage ('Copy artifcats to Production') {
            steps {
                timeout(time: 5, unit: 'DAYS') {
                input message:'Approve/Reject for prod deployment?'
                }
                build job: 'Code-Deploy-Prod'
            }
        }
    }
}