pipeline {
    agent any
    stages {
        stage ('Build Maven artifcat') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success{
                    archiveArtifacts artifacts: '**/*.war'
                }

            }
        }
        stage ('Copy artifcats to Staging') {
            steps {
                build job: 'Code-Deploy-Staging'
            }
       }
        // stage ('Copy artifcats to Production') {
        //     steps {
        //         build job: 'Code-Deploy-Prod'
        //     }
        // }
    }
}