pipeline {
    agent any
    stages {
        stage ('Build Maven artifcat') {
            steps {
                sh 'mvn -f java-tomcat-sample\pom.xml clean package'
            }
            post {
                success{
                    archiveArtifacts artifacts: '**/*.war'
                }

            }
        }
    }
}